### ISSUE TITLE
关于HSSNet自带的matconvnet的问题？

### ISSUE THREAD

**Issue by Bradyeyi** [QiaoLiuHit/HSSNet#1]
你好  @QiaoLiuHit :
         我使用代码中自带的matconvnet时会出现以下的BUG:
                       No property `poolSize` for a layer of type `dagnn.GlobalPooling`。
         我上网搜索了类似问题的问题，发现时matconvnet版本的问题，于是我自己去matconvnet的官网编译安装了最新版本，使用的环境是：matlab R2018b + VS2015 + Cuda9.1 + 对应7版本cudnn + contrib。编译完成后，代码调用最新的matconvnet依旧出现类似问题，之后我自己在网上找了两个解决方案依旧没有解决。
       这里希望您能够说明一下你原始编译安装matconvnet的环境，如果你能够提供编译好的matconvnet就再好不过！
谢谢！
祝好！

**Comment by QiaoLiuHit** [comment]
你好，我更新了经过编译的matconvnet，请下载新的版本，之前的版本漏掉了Globalpooling层。我的环境是ubuntu14+matlab2017a+cuda8.0。
